openapi: 3.0.0
info:
  title: "ala-showcase-api  \U0001F680"
  version: '1.0'
  contact:
    name: afwani shofiyulloh
    email: afwani123@gmail.com
  description: design api spec
servers:
  - url: 'http://localhost:3000/apis'
paths: {}
components:
  schemas:
    Partner:
      title: Partner
      type: object
      x-examples: {}
      properties:
        UUID:
          type: string
          format: uuid
          description: Partner Unique Identifier
        Type:
          type: string
          enum:
            - Driver
            - Warehose
          description: |-
            Partner Type (UUID) uuid : type
            (2debfd7a-2c9c-11ea-978f-2e728ce88125 => Driver)
            (2debfa82-2c9c-11ea-978f-2e728ce88125 => Warehouse)
          format: uuid
        Code:
          description: Partner code
          type: string
        Name:
          type: string
          description: Partner Username / Slug
        FullName:
          type: string
          description: Partner Full Name
        Logo:
          type: string
          description: Partner Logo URL
        Image:
          type: string
          description: Partner Image URL
        Latitude:
          type: string
          description: Partner Latitude
        Longitude:
          type: string
          description: Partner Longitude
        Address:
          type: string
          description: Partner Address
        Region:
          type: string
          description: Partner Region
    Category:
      type: object
      title: Category
      description: ''
      properties:
        UUID:
          type: string
          description: Category Unique Identifier
          format: uuid
        Code:
          type: string
          description: Category Code / Slug
        Image:
          type: string
          description: Category Name
        Description:
          type: string
          description: Category Image URL
        Order:
          type: string
          description: Category Index Order (int)
        IsDraft:
          type: string
          description: Category access is Draft or Public
          enum:
            - Draft
            - Public
          example: Draft
        DraftBy:
          type: string
          description: User who create the Category (if is draft) (uuid) (relation to partner)
          format: uuid
    Good:
      title: Good
      type: object
      properties:
        UUID:
          type: string
          description: Good Unique Identifier
          format: uuid
        Code:
          type: string
          description: Good Code / Slug
        Category:
          type: string
          description: Good Category (uuid) (Relation with Category)
          format: uuid
        Name:
          type: string
          description: Good Name
        Image:
          type: string
          description: Good Image URL
        Aliases:
          type: array
          description: Good Alias / Another Name (array string)
          items:
            type: string
        Description:
          type: string
          description: Good Description
        UnitType:
          type: string
          description: |-
            Good Unit Type
            - 15a481f2-af27-11ea-b3de-0242ac130004 : Grams
            - 15a4840e-af27-11ea-b3de-0242ac130004 : Kilograms
            - 15a48652-af27-11ea-b3de-0242ac130004 : Quantities
            - 15a487c4-af27-11ea-b3de-0242ac130004 : Liters
          format: uuid
        UnitValue:
          type: number
          description: Good Unit Value (number/float/double)
        IsFixed:
          type: boolean
          description: Good Fixed Unit flag (bool) (if true cannot order with custom)
        IsDraft:
          type: string
          description: Good access is Draft or Public
          enum:
            - Draft
            - Public
        DraftBy:
          type: string
          description: User who create the Category (if is draft) (uuid) (relation to partner)
          format: uuid
    Product:
      title: Product
      type: object
      description: this model not fix!
      properties:
        UUID:
          type: string
          format: uuid
        name:
          type: string
        price:
          type: string
        description:
          type: string
  securitySchemes:
    Anonymous-Token:
      name: X-Ala-Token
      type: apiKey
      in: header
  responses:
    unauthorized-res:
      description: 'Response for unauthorized request and validation token '
      content:
        application/json:
          schema:
            type: object
            properties:
              staus:
                type: number
                description: status-code
                example: 401
                default: 401
              messages:
                type: string
                description: Error Messages
                example: Require Api Token
                default: Require Api Token
              data:
                type: array
                items: {}
          examples:
            unauthorized-response-example:
              value:
                staus: 401
                messages: Require Api Token
                data:
                  - null
tags:
  - name: overview
